#!/usr/bin/env python3
from bio import DNA 
import re

# read and parse INI file
import configparser
params = dict()
config = configparser.ConfigParser()
config.read('dna.ini')
for section in config.sections():
    for option in config.options(section):
        params[option] = config.get(section, option)
s = params['dna']

## read and parse JSON file
#import json
#with open("dna.json", "r") as f: 
#   params = json.loads(f.read())
#s = params['basic']['dna']

## read and parse YAML file
#import yaml
#with open('dna.yaml','r') as f: 
#    params = yaml.load(f.read())
#s = params['basic']['dna']

## read and parse Namelist.input file
#for line in open('dna.in', 'rU'):
#    m = re.search('dna\s?=\s?(.*$)',line) # parameter
#    if m:
#        # Delete apostrophes and commas
#        s = re.sub(r"[',]", "", m.group(1))

print("string is: ", s)

dna1 = DNA(s)
print("Reverse complement is: ", dna1.reversecomplement()) 
print()
print("%G+C is:", dna1.gc()) 

nucs = dna1.nucleotides()
print("Nucleotides are:", nucs, len(nucs))
print()

din = dna1.dinucleotides()
print("Dinucleotides are:", din, len(din))
print()

codons = dna1.codons()
print("Codons are:", codons, len(codons))
print()



# output nucleotides to file
f = open('nucs.out','w')
for i, d in enumerate(nucs):
    #print i+1, d, nucs
    f.write( "\'" + d + "\' " + str(nucs[d]) + "\n") 

# output dinucleotides to file
f = open('din.out','w')
for i, d in enumerate(din):
    #print i+1, d, din[d]
    f.write( "\'" + d + "\' " + str(din[d]) + "\n") 

# output codons to file
f = open('codons.out','w')
for i, d in enumerate(codons):
    #print i+1, d, codons[d]
    f.write( "\'" + d + "\' " + str(codons[d]) + "\n") 

f.close()
