%include('header',title='confirm')
<body onload="init()">
%include('navbar')
<!-- This file was autogenerated from SciPaaS -->
<form action="/confirm" method="post">
<input type="hidden" name="app" value="{{app}}">
<input type="hidden" name="cid" value="{{cid}}">

<h2>Enter string of DNA to be analyzed:</h2>
<textarea name="dna" rows="4" cols="80">
{{dna}}
</textarea>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
            <button type="submit" class="btn btn-primary btn-default">
                Continue <em class="glyphicon glyphicon-forward"></em> 
            </button>
        </div>
    </div>
</div>

</form>
%include('apps/footer')
%include('footer')
