%include('header',title='confirm')
<body onload="init()">
%include('navbar')
%include('apps/alert')
<!-- This file was autogenerated from SciPaaS -->
<form action="/confirm" method="post">
<input type="hidden" name="app" value="{{app}}">
<input type="hidden" name="cid" value="{{cid}}">

<button type="submit" class="btn btn-success"> <!-- pull-right -->
Continue <em class="glyphicon glyphicon-forward"></em>
</button>

<h2>Enter string of DNA to be analyzed:</h2>
<textarea name="dna" rows="4" cols="80">
{{dna}}
</textarea>

</form>
%include('footer')
