%include header title='confirm'
<body onload="init()">
%include navbar
<!-- This file was autogenerated from SciPaaS -->
<form action="/{{app}}/confirm" method="post">
<input class="submit start" type="submit" value="confirm" />
<div class="tab-pane" id="tab-pane-1">
<div class="tab-page">
<h2 class="tab">basic</h2>
Enter string of DNA to be analyzed:<br>
<textarea name="dna" rows="4" cols="100">
{{dna}}
</textarea>
</div>
</div>
</form>
%include footer
