%include header title='confirm'
<body onload="init()">
%include navbar
<!-- This file was autogenerated from SciPaaS -->
<form action="/{{app}}/confirm" method="post">
<input class="start" type="submit" value="confirm" />
<div class="tab-pane" id="tab-pane-1">
<div class="tab-page">
<h2 class="tab">basic</h2>
<table><tbody>
<tr><td>hello:</td>
<td><input type="text" name="hello" value="{{hello}}"/></td></tr>
</tbody></table>
</div>
</div>
</form>
%include footer
