#!/usr/bin/env python

import apps
import sys
import os

sys.argv[1:]

mendel = apps.app_f90('mendel')

try:
    if(sys.argv[1] == "n"):
        params = mendel.read_params()
        if mendel.write_html_template():
		    print "successfully output template"

    if(sys.argv[1] == "s"):
        os.system("python main.py")

except:
    print "usage: " + sys.argv[0] + " <command>"
    print
    print "list of commands:"
    print "n - create new project"
    print "s - start the web server"
