#!/usr/bin/env python

import config
import sys
import os

sys.argv[1:]

try:
    if(sys.argv[1] == "new"):
        params = config.read_namelist()
        if config.write_html_template():
		    print "successfully output template"

    if(sys.argv[1] == "st"):
        os.system("python startup.py")

except:
    print "usage: " + sys.argv[0] + " <command>"
    print
    print "list of commands:"
    print "new - create new project"
