#!/bin/bash

# if the server is already running then don't start it again
if $(curl --output /dev/null --silent --head --fail http://localhost:8580)
then
    echo "SERVER ALREADY RUNNING"
    open 'http://0.0.0.0:8580/'
    exit
fi 

# start the server
cd "$( dirname "${BASH_SOURCE[0]}" )"
./spc run >& log &
pid=$!
echo "STARTING SERVER PLEASE WAIT..."

# test if the server is up
var=0
until $(curl --output /dev/null --silent --head --fail http://0.0.0.0:8580); do
    printf '.'
    sleep 1
    if ((++var >= 10)); then
        echo
        echo "TIMEOUT REACHED... THERE MAY BE A PROBLEM STARTING THE SERVER" 
        echo "but trying anyway to visit the site http://0.0.0.0:8580/"
        read option
    fi 
done

# open the site in the web browser
open 'http://0.0.0.0:8580/'

