%include header title='confirm'
<body onload="init()">
%include navbar
<!-- This file was autogenerated from SciPaaS -->
<form action="/{{app}}/confirm" method="post">
<input class="start" type="submit" value="confirm" />
<div class="tab-pane" id="tab-pane-1">
<div class="tab-page">
<h2 class="tab">basic</h2>
<table><tbody>
<tr><td>case_id:</td>
<td><input type="text" name="case_id" value="{{case_id}}"/></td></tr>
<tr><td>dna:</td>
<td><input type="text" name="dna" value="{{dna}}"/></td></tr>
</tbody></table>
</div>
</div>
</form>
%include footer