%include header title='confirm'
<body onload="init()">
%include navbar
<!-- This file was autogenerated from SciPaaS -->
<form action="/{{app}}/confirm" method="post">
<input class="start" type="submit" value="confirm" />
<div class="tab-pane" id="tab-pane-1">
</div>
</form>
%include footer